version: '3.8'

services:
  tg-bot:
    restart: unless-stopped
    build: ./
    command: sh -c "./wait-for-pg.sh db && npx prisma migrate deploy && yarn start"
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_PASS: ${DATABASE_PASSWORD}
    volumes:
      - ./src/constants:/app/src/constants
      - ./static:/app/static
  db:
    restart: always
    build:
      context: ./pgdb
      dockerfile: Dockerfile
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      retries: 10
